// Mock data for the app
export const academicResources = [
    {
      id: "1",
      title: "Introduction to Economics",
      type: "Notes",
      university: "University of Cape Town",
      subject: "Economics",
      downloads: 1245,
      rating: 4.7,
      url: "https://example.com/resource1",
    },
    {
      id: "2",
      title: "Advanced Calculus Past Paper 2024",
      type: "Past Paper",
      university: "University of the Witwatersrand",
      subject: "Mathematics",
      downloads: 879,
      rating: 4.5,
      url: "https://example.com/resource2",
    },
    {
      id: "3",
      title: "Organic Chemistry Tutorial",
      type: "Tutorial",
      university: "University of Pretoria",
      subject: "Chemistry",
      downloads: 1567,
      rating: 4.8,
      url: "https://example.com/resource3",
    },
    {
      id: "4",
      title: "Software Engineering Principles",
      type: "Notes",
      university: "University of KwaZulu-Natal",
      subject: "Computer Science",
      downloads: 2134,
      rating: 4.9,
      url: "https://example.com/resource4",
    },
    {
      id: "5",
      title: "Introduction to Psychology",
      type: "Notes",
      university: "University of the Free State",
      subject: "Psychology",
      downloads: 1876,
      rating: 4.6,
      url: "https://example.com/resource5",
    },
  ];
  
  export const collaborationSpaces = [
    {
      id: "1",
      title: "AI Ethics Research Group",
      members: 24,
      universities: ["University of Cape Town", "University of the Witwatersrand"],
      description: "Exploring ethical implications of AI in South African context",
      tags: ["AI", "Ethics", "Research"],
      isActive: true,
    },
    {
      id: "2",
      title: "Renewable Energy Solutions",
      members: 18,
      universities: ["University of Pretoria", "University of KwaZulu-Natal"],
      description: "Developing sustainable energy solutions for rural communities",
      tags: ["Energy", "Sustainability", "Engineering"],
      isActive: true,
    },
    {
      id: "3",
      title: "South African Literature Circle",
      members: 15,
      universities: ["University of the Free State", "University of Cape Town"],
      description: "Analyzing contemporary South African literature",
      tags: ["Literature", "Culture", "Analysis"],
      isActive: true,
    },
    {
      id: "4",
      title: "Healthcare Innovation Hub",
      members: 32,
      universities: ["University of the Witwatersrand", "University of KwaZulu-Natal"],
      description: "Creating innovative healthcare solutions for underserved areas",
      tags: ["Healthcare", "Innovation", "Social Impact"],
      isActive: true,
    },
  ];
  
  export const careerOpportunities = [
    {
      id: "1",
      title: "Software Developer Intern",
      company: "Standard Bank",
      location: "Johannesburg",
      type: "Internship",
      deadline: "2025-07-15",
      requirements: ["Computer Science", "Programming"],
    },
    {
      id: "2",
      title: "Marketing Assistant",
      company: "Woolworths",
      location: "Cape Town",
      type: "Part-time",
      deadline: "2025-06-30",
      requirements: ["Marketing", "Communication"],
    },
    {
      id: "3",
      title: "Research Assistant - Renewable Energy",
      company: "CSIR",
      location: "Pretoria",
      type: "Full-time",
      deadline: "2025-07-10",
      requirements: ["Engineering", "Research"],
    },
    {
      id: "4",
      title: "Finance Graduate Programme",
      company: "Investec",
      location: "Durban",
      type: "Graduate Programme",
      deadline: "2025-08-01",
      requirements: ["Finance", "Accounting"],
    },
  ];
  
  export const wellnessResources = [
    {
      id: "1",
      title: "Stress Management Workshop",
      type: "Workshop",
      provider: "UCT Student Wellness",
      date: "2025-06-20",
      location: "Online",
      description: "Learn effective techniques to manage exam stress",
    },
    {
      id: "2",
      title: "Mindfulness Meditation Sessions",
      type: "Recurring Event",
      provider: "Wits Counseling Center",
      date: "Every Tuesday",
      location: "Online",
      description: "Weekly guided meditation sessions for mental wellbeing",
    },
    {
      id: "3",
      title: "Sleep Hygiene Guide",
      type: "Resource",
      provider: "UP Health Services",
      date: "Always Available",
      location: "Digital Resource",
      description: "Comprehensive guide to improving sleep quality",
    },
    {
      id: "4",
      title: "Peer Support Network",
      type: "Support Group",
      provider: "UKZN Student Services",
      date: "Ongoing",
      location: "Various Campuses",
      description: "Connect with trained peer supporters for emotional assistance",
    },
  ];
  
  export const notifications = [
    {
      id: "1",
      title: "NSFAS Application Update",
      message: "Your NSFAS application status has been updated. Tap to view details.",
      date: "2025-06-10T09:30:00",
      read: false,
      type: "financial" as const,
    },
    {
      id: "2",
      title: "Assignment Deadline Reminder",
      message: "Your Economics 101 assignment is due in 48 hours.",
      date: "2025-06-09T14:15:00",
      read: true,
      type: "academic" as const,
    },
    {
      id: "3",
      title: "New Collaboration Request",
      message: "You've been invited to join 'AI Ethics Research Group'.",
      date: "2025-06-08T11:45:00",
      read: false,
      type: "collaboration" as const,
    },
    {
      id: "4",
      title: "Wellness Workshop Tomorrow",
      message: "Reminder: Stress Management Workshop starts at 14:00 tomorrow.",
      date: "2025-06-07T16:20:00",
      read: true,
      type: "wellness" as const,
    },
    {
      id: "5",
      title: "New Career Opportunity",
      message: "New internship opportunity matching your profile has been posted.",
      date: "2025-06-06T10:05:00",
      read: false,
      type: "career" as const,
    },
  ];